name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
        
      - name: Verify package
        run: dart pub publish --dry-run
        
      - name: Publish to pub.dev
        run: dart pub publish --force
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.REPO_TOKEN_FLUTTER_PKG }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            CHANGELOG.md
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_FLUTTER_PKG }} 